apiVersion: v1
kind: Service
metadata:
  name:  techtrends
  namespace: sandbox
spec:
  selector:
    app:  techtrends
  type:  ClusterIP
  ports:
  - port:  4111
    targetPort:  3111
    protocol: TCP
